version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: media-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: media_queue
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: media-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data: